name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        architecture: [x86, x64]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore Frituquim/Frituquim.csproj
      
    - name: Download yt-dlp
      run: |
        $ytdlpUrl = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe"
        $outputPath = "yt-dlp.exe"
        Invoke-WebRequest -Uri $ytdlpUrl -OutFile $outputPath
        Write-Host "Downloaded yt-dlp.exe"
        
    - name: Publish ${{ matrix.architecture }}
      run: |
        dotnet publish Frituquim/Frituquim.csproj `
          --configuration Release `
          --runtime win-${{ matrix.architecture }} `
          --self-contained true `
          --output publish-${{ matrix.architecture }} `
          --property:PublishSingleFile=true `
          --property:IncludeNativeLibrariesForSelfExtract=true `
          --property:PublishTrimmed=false `
          --verbosity normal
          
    - name: Copy yt-dlp to publish directory
      run: |
        Copy-Item "yt-dlp.exe" "publish-${{ matrix.architecture }}/yt-dlp.exe"
        
    - name: Create release package
      run: |
        $archiveName = "Frituquim-${{ matrix.architecture }}.zip"
        Compress-Archive -Path "publish-${{ matrix.architecture }}/*" -DestinationPath $archiveName
        Write-Host "Created $archiveName"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Frituquim-${{ matrix.architecture }}
        path: Frituquim-${{ matrix.architecture }}.zip
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          Frituquim-x86/Frituquim-x86.zip
          Frituquim-x64/Frituquim-x64.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
